In [ ]:
#!pip install transformers

In [1]:
import pandas as pd
import numpy as np
import torch
from transformers import BertForQuestionAnswering
from transformers import BertTokenizer

In [11]:
path = "/Users/kazotogbah/Desktop/CapstoneWritting/hmh_data/grade5_teachers_guide_pal_corpus_clean_keywords_sumy_distilroberta34b1dc07f9547647fb90760ba6630e5f92fd7af8e4a0d66a84cc084020f76b2d.pkl" 
teachersGuidePal = pd.read_pickle(path,compression='infer')
teachersGuidePal

,file,page,text,content_type,Skill Title,Skill Description,Skill GUID,Skill Code,strand,strand_description,...,Skill Title_embedded,Skill Description_embedded,strand_embedded,Skill Title_no_periods_embedded,Skill Description_no_periods_embedded,strand_no_periods_embedded,strand_description_no_periods_embedded,skill_description_keywords_embedded,strand_description_keywords_embedded,text_clean_summarized_embedded
0,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,1.0,MODULE\n˜\nﬁ I will not follow \nwhere the pat...,content,module i will not follow where the path may le...,module i will not follow where the path may le...,nan,nan,module i will not follow where the path may le...,module i will not follow where the path may le...,...,"[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.28464243, 0.2220484, 0.4422115, 0.0465012, ...","[0.28464243, 0.2220484, 0.4422115, 0.0465012, ...","[0.20862822, -0.033599023, 0.044862866, 0.2881..."
1,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,2.0,MODULE\n˜\nﬁ I will not follow \nwhere the pat...,content,module i will not follow where the path may le...,module i will not follow where the path may le...,nan,nan,module i will not follow where the path may le...,module i will not follow where the path may le...,...,"[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.30782643, 0.058543533, 0.16792017, 0.085862...","[0.30782643, 0.058543533, 0.16792017, 0.085862...","[0.16788949, -0.13963626, -0.07024216, 0.53562..."
2,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,3.0,˜˚˛˝˙ˆˇ˘˝\n\nˆˇ\nThe words in the chart will h...,content,the words in the chart will help you talk and ...,the words in the chart will help you talk and ...,nan,nan,the words in the chart will help you talk and ...,the words in the chart will help you talk and ...,...,"[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.318849, 0.5429922, 0.2398742, -0.08303005, ...","[0.318849, 0.5429922, 0.2398742, -0.08303005, ...","[0.23586863, 0.037411276, 0.0036898185, 0.0774..."
3,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,4.0,˜˚˛˝˙ˆˇ˘˝\n\nˆˇ\nThe words in the chart will h...,content,the words in the chart will help you talk and ...,the words in the chart will help you talk and ...,nan,nan,the words in the chart will help you talk and ...,the words in the chart will help you talk and ...,...,"[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.34651068, 0.33815506, 0.31886512, -0.218285...","[0.34651068, 0.33815506, 0.31886512, -0.218285...","[0.13544446, 0.15687963, -0.033667527, -0.0243..."
4,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,5.0,˜\n˚˛˝˙˜\n\nReasons to \nInvent\nSolve \nProbl...,content,reasons to invent solve problems achieve fame ...,reasons to invent solve problems achieve fame ...,nan,nan,reasons to invent solve problems achieve fame ...,reasons to invent solve problems achieve fame ...,...,"[0.2885548, 0.023478366, 0.30554906, 0.3569067...","[0.2885548, 0.023478366, 0.30554906, 0.3569067...","[0.2885548, 0.023478366, 0.30554906, 0.3569067...","[0.2572909, 0.11252953, 0.25145745, 0.29272386...","[0.2572909, 0.11252953, 0.25145745, 0.29272386...","[0.2572909, 0.11252953, 0.25145745, 0.29272386...","[0.2572909, 0.11252953, 0.25145745, 0.29272386...","[0.21129978, 0.31341118, 0.3093127, 0.29272902...","[0.21129978, 0.31341118, 0.3093127, 0.29272902...","[0.27298772, 0.018115517, 0.27320105, 0.338362..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5577,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write haikus or tankas,write haikus or tankas following the structura...,e0653513-1af9-493c-99cc-ca26440a59cb,WT.WP.2.C4,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[-0.24465016, -0.41559923, -0.22348292, -0.189...","[-0.14750454, -0.020040585, -0.3024932, -0.139...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.24465016, -0.41559923, -0.22348292, -0.189...","[-0.14750454, -0.020040585, -0.3024932, -0.139...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.065458834, -0.022467336, -0.14402398, -0.1...","[-0.16295668, -0.059479393, -0.22297119, -0.04...","[0.15197246, -0.00865834, -0.2474561, -0.14950...","[-0.035868734, -0.07316666, -0.20177855, -0.15..."
5578,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write riddle poems,write riddle poems that require the reader to ...,97410ba5-9fc4-4684-97c4-9be529ceafe5,WT.WP.2.C5,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[-0.1577658, -0.096144654, -0.15173835, 0.1961...","[-0.2399435, -0.15688682, -0.09092543, -0.1290...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.1577658, -0.096144654, -0.15173835, 0.1961...","[-0.2399435, -0.15688682, -0.09092543, -0.1290...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.14212829, -0.087659754, 0.0151685495, -0.1...","[-0.2681789, -0.12879677, 0.017346552, -0.3627...","[0.05806018, 0.06841876, -0.053806134, -0.1370...","[-0.08528366, -0.17463017, -0.021595858, -0.16..."
5579,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write odes,write odes to praise people events objects or ...,d5d3e7af-d5b5-45f9-8320-77db880d3856,WT.WP.2.C6,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[0.22441971, -0.30364242, 0.34133807, -0.45593...","[0.38578078, 0.07033281, 0.098516926, -0.27138...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[0.22441971, -0.30364242, 0.34133807, -0.45593...","[0.38578078, 0.07033281, 0.098516926, -0.27138...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[0.016466925, -0.037565004, 0.065129966, -0.15...","[0.48021975, -0.18707027, -0.0040784995, 0.037...","[0.27416033, 0.013461181, 0.005883138, -0.0807...","[0.05119294, -0.12402764, 0.02975093, -0.16433..."
5580,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write sonnets,write sonnets following the structural charact...,7637f149-07f8-4ca0-84d7-5593e1b9211a,WT.WP.2.C7,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[-0.3031502, 0.4306519, 0.087189816, 0.1234787...","[-0.21402566, 0.4978751, -0.04160893, 0.137464...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.3031502, 0.4306519, 0.087189816, 0.1234787...","[-0.21402566, 0.4978751, -0.04160893, 0.137464...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.1443302, 0.115797274, 0.0013336517, 0.0579...","[-0.11399182, 0.3713151, -0.121542305, 0.20513...","[0.14028896, 0.2253419, -0.05671437, 0.1401694...","[-0.10235442, 0.053097203, -0.021812407, 0.012..."
5581,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write free verse poems,write poems in free verse that depart from tra...,d774010e-382b-417f-842b-21dcc46a5a65,WT.WP.2.C8,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[-0.26282188, -0.2267464, 0.063811034, -0.3585...","[-0.14395787, 0.20046626, 0.066164464, -0.3402...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.26282188, -0.2267464, 0.063811034, -0.3585...","[-0.14395787, 0.20046626, 0.066164464, -0.3402...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.1202832, 0.020569142, 0.08610445, -0.27497...","[0.1200044, 0.022991914, 0.19192894, -0.269595...","[0.19046833, 0.14302915, -0.020604758, -0.1473...","[-0.047682863, -0.05864437, 0.059854243, -0.29..."

In [12]:
## collect page content and skill description
import pandas as pd
import numpy as np
pal_skills2 = []
pal_content2 = []
page = -1
for text in teachersGuidePal['content_type']:
    page = page+1
    if teachersGuidePal['content_type'][page]== "content":
        pal_content2.append(teachersGuidePal['Skill Description'][page])
    else:
        pal_skills2.append(teachersGuidePal['Skill Description'][page])

In [13]:
# concatenate question question words
import pandas as pd
import numpy as np
skills_to_Quest = []
skillnum = -1
concat_1 = "How to "
concat_2 = "?"
for skill in pal_skills2:
    skillnum = skillnum+1
    skills_to_Quest.append(concat_1 + pal_skills2[skillnum] + concat_2)
    
skills_to_Quest

["How to identify an informational text's intended audience while reading and analyze how it affects the author's development of a text?",
 "How to understand that authors write texts for different purposes to inform persuade entertain or share thoughts or feelings and identify author's purpose(s) while reading text?",
 'How to while reading analyze how the author advances the purpose of a text in terms of style and use of text structure language and rhetoric (e.g. formal or informal language figures of speech tone persuasiveness) and evaluate the degree to which the author achieved the purpose of the text?',
 "How to determine the author's perspective and opinions including underlying values and beliefs based on explicit and implicit information while reading text?",
 "How to identify and analyze an author's qualifications to evaluate the author's credibility?",
 "How to while reading evaluate how an author's personal cultural and historical background impacts their purpose for writing and the structure and meaning of a text?",
 "How to distinguish the author's opinions from one's own opinions while reading text?",
 "How to while reading identify an author's opinions beliefs and attitudes that bias text based on explicit and implicit information from the text or information about the author's background?",
 "How to evaluate how an author's perspective or opinions impact a text while reading?",
 "How to while reading compare and contrast how different authors' personal cultural and historical backgrounds impact their purpose for writing and the structure and meaning of the texts they write?",
 "How to identify the author's purpose in individual paragraphs or sections of a text?",
 'How to set a purpose for reading text?',
 "How to preview the text to gain information about a text's author genre topic and structure creating a context to inform the text's meaning and significance while reading?",
 'How to make and confirm or refute predictions while reading in order to engage with a text and deepen comprehension?',
 "How to make personal connections between a text and one's own experiences feelings and perspectives to actively read and comprehend deeply?",
 'How to connect a text to what is known about the world and the way things are outside the self to actively read and comprehend deeply?',
 'How to connect information between texts during or after reading to aid with comprehending the new text and to broaden knowledge and gain new perspectives?',
 "How to ask and answer questions while reading to help clarify comprehension deepen understanding of a text's literal meaning and demonstrate comprehension?",
 'How to ask and answer interpretive and evaluative questions while reading to support comprehension and analysis of a text and demonstrate comprehension?',
 'How to visualize situations while reading to develop a deeper understanding and enhance recall of the text?',
 'How to use graphic organizers to aid in comprehension and analysis of text while reading or for later use?',
 'How to use note taking and annotation strategies while reading to monitor comprehension of text or for later use?',
 'How to while reading periodically check for coherence and understanding of main ideas events and concepts?',
 'How to when comprehension breaks down during reading use strategies to adjust such as rereading adjusting reading rate reading ahead summarizing or questioning difficult parts of the text?',
 "How to combine information gained from reading a text with one's own academic and personal knowledge to make inferences about what is not stated directly?",
 'How to distinguish between works of fiction and nonfiction while reading based on text content and features?',
 'How to choose texts for independent reading based on personal preferences of topics authors and genres or reviews or recommendations?',
 'How to access prior knowledge to support comprehension and evaluation of a text while reading?',
 'How to adjust reading style (e.g. skimming re reading close reading) based on purpose for reading?',
 'How to build background knowledge to support comprehension and evaluation of a text while reading?',
 'How to while reading distinguish true realistic and fantastical literary works and elements of literary works?',
 'How to generalize information gained from reading a text to make a prediction about a related situation or text?',
 'How to distinguish between literary and informational texts while reading?',
 'How to evaluate the plausibility of predictions about text based on text evidence while reading?',
 'How to draw conclusions from reading text based on a combination of information from the text and background knowledge to make decisions arrive at opinions or determine results?',
 'How to use a combination of information from text and background knowledge to make valid generalizations about a subject based on reading?',
 'How to cite text details examples and evidence from reading to support inferences conclusions interpretations and arguments?',
 'How to engage in classroom small group or partner conversations about the text during and after reading to build on thoughts and ideas and to deepen understanding of the text?',
 'How to write a response to text after reading to share thoughts feelings ideas or opinions about what was read to aid recall or to deepen comprehension?',
 'How to respond to a text after reading by creating an illustration that recounts events ideas and details about the text?',
 'How to while reading analyze the connections relationships or interactions between individuals ideas or events in a text and explain how they develop throughout the course of the text?',
 'How to while reading compare and contrast works of fiction to works of nonfiction that are about the same or similar topic events or people?',
 "How to while reading analyze how a selection from a text fits into the overall structure of the text and contributes to the text's development?",
 'How to while reading evaluate the degree to which the meaning of a text is clear or ambiguous and the information in a text is consistent or inconsistent and determine the impact on the meaning and significance of the text?',
 'How to evaluate how different mediums present the same text or topic (e.g. books oral performances presentations films) and evaluate similarities and differences in how each medium interprets or represents it?',
 'How to distinguish between an objective summary and a critique or review of text?',
 'How to evaluate summaries of text for accuracy meaning or objectivity?',
 'How to compare and contrast the structure and organization of two or more informational texts while reading?',
 'How to synthesize ideas from reading texts across genres to draw conclusions about the texts and develop knowledge?',
 'How to reflect and respond from a personal perspective (e.g. level of personal enjoyment what was learned agreement/disagreement) after reading text?',
 'How to evaluate the quality and relevance of evidence from text when citing evidence to support inferences conclusions interpretations and arguments?',
 "How to paraphrase texts or parts of texts in one's own words after reading retaining the meaning structure and order of the text?",
 'How to synthesize ideas from different parts within a text while reading to understand how the ideas fit together and contribute to the overall significance of the text?',
 'How to synthesize ideas from written texts with texts read aloud and/or media to draw conclusions and develop knowledge?',
 'How to summarize texts objectively after reading providing a shortened version of the text that retains the main points?',
 'How to orally summarize texts objectively after reading providing a shortened version of the text that retains the main points?',
 'How to write objective summaries of text after reading providing a shortened version of the text that retains the main points?',
 'How to collaborate to produce writing or media after reading text?',
 "How to understand that graphic features such as illustrations maps or charts contribute to a text's meaning and identify interpret and use graphic features while reading?",
 'How to while reading evaluate the degree to which the graphic features in a text contribute important information that cannot be conveyed by the words alone?',
 'How to understand that text features including chapters headings sub headings and bullets are used to provide organization and visual interest to a text and identify interpret and use text features to locate information while reading text?',
 'How to evaluate the degree to which text features support comprehension while reading text?',
 'How to synthesize information from multiple graphic features to draw conclusions while reading text?',
 'How to understand that information is provided by graphic features and by words and distinguish information that is provided by graphics and by words while reading text?',
 'How to integrate information from text features and/or graphic features to comprehend text while reading?',
 "How to understand that imagery consists of words that appeal to readers' senses and identify imagery while reading text?",
 'How to understand that parallelism is a repetition of grammatically identical words or phrases in a sentence to give it a balance and rhythm and identify parallelism while reading text?',
 "How to while reading text evaluate the degree to which parallelism provides balance and rhythm to a sentence and supports the author's purpose?",
 'How to understand that dialogue is a conversation between two or more characters and identify dialogue while reading text?',
 'How to understand that a dialect is the way a group of people speak a language based on location or background and that authors use dialect to help define characters and identify the use of dialects while reading text?',
 'How to while reading text evaluate the degree to which use of dialects helps define characters?',
 'How to understand that register is the degree of formality in language and identify register while reading text?',
 'How to while reading evaluate the degree to which use of register helps define characters and sets the tone of a work of literature?',
 'How to understand that mood is the emotional atmosphere conveyed by an author and identify the mood of a text while reading?',
 "How to while reading analyze the details that helped create a text's mood and evaluate their effectiveness?",
 "How to understand that tone conveys an author's attitudes and viewpoints toward the topic of the literary work and identify the tone of a text while reading?",
 "How to while reading analyze an author's tone or attitude toward a topic and identify details that communicate the tone?",
 "How to understand that an author's style is the overall voice of the author based on use of language and literary devices to give the work meaning and describe authors' styles while reading?",
 'How to while reading classical and modern works of literature identify and compare and contrast archetypes?',
 'How to while reading classical and modern works of literature identify and compare and contrast motifs?',
 'How to understand that language can be used literally and figuratively and identify literal and figurative uses of language while reading text?',
 "How to while reading analyze the use of figurative language for imagery or rhetorical effect and evaluate its impact on a text and the degree to which it advances the author's purpose?",
 "How to while reading text analyze how use of idioms impacts tone and advances the author's purpose?",
 'How to understand that oxymorons are combinations of words with contrasting meanings and that paradoxes are combinations of self contradictory statements and identify oxymorons and paradoxes while reading?',
 "How to while reading text analyze how use of contradictory language including oxymorons and paradoxes impacts tone and advances the author's purpose in a text?",
 "How to while reading text analyze author's use of literary devices to determine how they impact a text and the degree to which they achieve their purposes?",
 'How to understand that an anecdote is a very short story about an incident that can add meaning interest and informal evidence to a text or dialogue through qualities such as humor inspiration or a personal memory and identify anecdotes while reading text?',
 'How to evaluate the degree to which anecdotes achieve their purpose while reading text?',
 'How to understand that stereotyping is the attribution of a trait or traits to all members of a group rather than treating group members as individuals with many different traits and identify examples of stereotyping while reading text?',
 "How to analyze examples of imagery while reading text to determine which senses they appeal to and the degree to which they add to the reader's experience?",
 "How to while reading text evaluate the degree to which stereotyping impacts the text's development?",
 "How to while reading text analyze an author's use of euphemisms and evaluate how they are used to soften the author's message?",
 "How to understand that euphemisms are words or phrases that are more polite or indirect and used to soften another word or phrase or to neutralize a word's connotation and identify and interpret euphemisms while reading text?",
 "How to while reading text analyze an author's voice or style to understand the author's attitude and evaluate the impact of voice on the meaning the text?",
 "How to while reading text analyze how use of puns impacts tone and advances the author's purpose?",
 'How to understand that sound devices use patterns of sound repetition or words that suggest sounds to impact the meaning and mood of writing and identify sound devices such as assonance consonance alliteration or onomatopoeia while reading text?',
 'How to while reading text evaluate how use of sound devices impacts the meaning and mood of the text and enhances its aesthetic qualities?',
 "How to while reading compare and contrast different authors' use of literary devices to determine how they impact the texts and the degree to which they achieve their purposes?",
 'How to understand that idioms are phrases that have a specific meaning different from their literal meaning and identify idioms while reading text?',
 'How to understand that authors repeat words and phrases for emphasis and identify repetition in while reading text?',
 'How to understand that proverbs and adages are phrases that communicate general truths or advice that go beyond their literal meaning and identify proverbs and adages while reading text?',
 'How to understand that extended metaphors are figurative comparisons developed at length throughout literary works and identify examples of extended metaphors while reading text?',
 'How to while reading text analyze the meaning of extended metaphors and the degree to which they achieve their purpose?',
 'How to understand that similes and metaphors draw comparisons between two different ideas or things but that similes use "like" or "as" to draw the comparison and metaphors do not and identify similes and metaphors while reading text?',
 'How to while reading text analyze the purposes of similes and metaphors and the degree to which they achieve their purposes?',
 'How to understand that analogies use similes and metaphors to compare two very different things and identify analogies while reading text?',
 'How to while reading text analyze the effects that analogies have on the meaning of what they compare?',
 'How to understand that personification attributes human qualities to animals ideas and objects and identify personification while reading text?',
 "How to while reading text analyze examples of personification and evaluate how they affect the readers' perspective of the object of personification?",
 'How to understand that a symbol is an object that represents something else and gives it a special and deeper meaning and identify symbols and interpret what they represent while reading text?',
 "How to while reading text analyze why an author used symbols and how the symbols added to the reader's understanding of the text?",
 'How to understand that allegories are narratives told on literal and symbolic levels in order to communicate about abstract ideas and identify examples of allegories while reading text?',
 'How to while reading text analyze the meanings of the symbolism found in allegories and evaluate their effectiveness in communicating the message of the text?',
 'How to understand that an allusion is a short indirect reference to a person or thing that has a particular significance (e.g. cultural historical) and identify allusions while reading text?',
 'How to evaluate the degree to which an allusion achieves its purpose in a text while reading?',
 'How to understand that irony uses language to convey a message that is different from its literal meaning and identify and interpret irony while reading text?',
 'How to understand the similarities and differences between verbal situational and dramatic irony and identify each type while reading?',
 'How to while reading evaluate the degree to which irony deepens understanding of and adds interest to text?',
 'How to understand that sarcasm uses ironic language to mock insult or convey contempt and identify and interpret sarcasm while reading text?',
 'How to while reading text evaluate the degree to which sarcasm deepens understanding of and adds interest?',
 'How to understand that hyperbole is an extreme exaggeration to emphasize a point or for dramatic effect and identify hyperbole while reading text?',
 "How to while reading text evaluate the degree to which hyperbole emphasizes points and impacts the reader's interest?",
 "How to understand that satire is a device that points out a person's or group's negative qualities by using humor exaggeration and irony for the purpose of exposing those qualities and identify examples of satire while reading?",
 'How to while reading evaluate the degree to which satirical texts achieve their purpose?',
 "How to while reading text evaluate the degree to which an author's word choices are clear accurate and appropriate to convey the author's message effectively?",
 'How to identify the topic that the author addresses in a informational text while reading?',
 'How to identify text level main ideas in informational texts while reading?',
 'How to identify paragraph or section level main ideas in informational text while reading?',
 'How to while reading identify key details that support the main ideas of texts paragraphs or sections of text?',
 'How to identify and analyze conflicting information across two or more informational texts while reading?',
 'How to while reading informational text analyze the development of main ideas and the use of key details to support them?',
 'How to identify paragraph or section level topics in informational texts while reading?',
 'How to while reading evaluate the importance and relevance of key details that support the main ideas of informational texts paragraphs or sections of text?',
 "How to understand that scope is a text's coverage of a topic which can range from narrow (covering few details related to a topic) to broad (covering many details related to a topic) and identify the scope of informational texts while reading?",
 'How to identify individuals ideas concepts or events in informational texts while reading?',
 'How to identify sequential or chronological order of events or steps in a process in informational text while reading using signal words and clues as aids (e.g. now then once already before during after and then and dates [days months years])?',

In [14]:
contexts=[]
questions = []
for i in range(10):
    questions.append(skills_to_Quest[i])
    contexts.append(pal_content2[i])
    i=i+1

questions[9]

"How to while reading compare and contrast how different authors' personal cultural and historical backgrounds impact their purpose for writing and the structure and meaning of the texts they write?"

In [2]:
coqa = pd.read_json('http://downloads.cs.stanford.edu/nlp/data/coqa/coqa-train-v1.0.json')
coqa.head()

   version                                               data
0        1  {'source': 'wikipedia', 'id': '3zotghdk5ibi9ce...
1        1  {'source': 'cnn', 'id': '3wj1oxy92agboo5nlq4r7...
2        1  {'source': 'gutenberg', 'id': '3bdcf01ogxu7zdn...
3        1  {'source': 'cnn', 'id': '3ewijtffvo7wwchw6rtya...
4        1  {'source': 'gutenberg', 'id': '3urfvvm165iantk...

In [3]:
del coqa["version"]

In [4]:
coqa.head()

                                                data
0  {'source': 'wikipedia', 'id': '3zotghdk5ibi9ce...
1  {'source': 'cnn', 'id': '3wj1oxy92agboo5nlq4r7...
2  {'source': 'gutenberg', 'id': '3bdcf01ogxu7zdn...
3  {'source': 'cnn', 'id': '3ewijtffvo7wwchw6rtya...
4  {'source': 'gutenberg', 'id': '3urfvvm165iantk...

In [5]:
#required columns in our dataframe
cols = ["text","question","answer"]
#list of lists to create our dataframe
comp_list = []
for index, row in coqa.iterrows():
    for i in range(len(row["data"]["questions"])):
        temp_list = []
        temp_list.append(row["data"]["story"])
        temp_list.append(row["data"]["questions"][i]["input_text"])
        temp_list.append(row["data"]["answers"][i]["input_text"])
        comp_list.append(temp_list)
new_df = pd.DataFrame(comp_list, columns=cols) 
#saving the dataframe to csv file for further loading
new_df.to_csv("CoQA_data.csv", index=False)

In [6]:
data = pd.read_csv("CoQA_data.csv")
data.head()

,text,question,answer
0,"The Vatican Apostolic Library (), more commonl...",When was the Vat formally opened?,It was formally established in 1475
1,"The Vatican Apostolic Library (), more commonl...",what is the library for?,research
2,"The Vatican Apostolic Library (), more commonl...",for what subjects?,"history, and law"
3,"The Vatican Apostolic Library (), more commonl...",and?,"philosophy, science and theology"
4,"The Vatican Apostolic Library (), more commonl...",what was started in 2014?,a project

In [7]:
print("Number of question and answers: ", len(data))

Number of question and answers:  108647

In [8]:
model = BertForQuestionAnswering.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')
tokenizer = BertTokenizer.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')

In [9]:
from torch.utils.data import DataLoader
from transformers import AdamW

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

_ = model.to(device)

In [15]:
random_num = np.random.randint(0,len(data))
question = questions[0] #data["question"][random_num]
text = contexts[5] #data["text"][random_num]

In [16]:
input_ids = tokenizer.encode(question, text)
print("The input has a total of {} tokens.".format(len(input_ids)))

The input has a total of 158 tokens.

In [17]:
tokens = tokenizer.convert_ids_to_tokens(input_ids)
for token, id in zip(tokens, input_ids):
    print('{:8}{:8,}'.format(token,id))

[CLS]        101
how        2,129
to         2,000
identify   6,709
an         2,019
information   2,592
##al       2,389
text       3,793
'          1,005
s          1,055
intended   3,832
audience   4,378
while      2,096
reading    3,752
and        1,998
analyze   17,908
how        2,129
it         2,009
affects   13,531
the        1,996
author     3,166
'          1,005
s          1,055
development   2,458
of         1,997
a          1,037
text       3,793
?          1,029
[SEP]        102
reasons    4,436
to         2,000
in         1,999
##vent    15,338
solve      9,611
problems   3,471
achieve    6,162
fame       4,476
and        1,998
fortune    7,280
14         2,403
do         2,079
not        2,025
edit      10,086
changes    3,431
must       2,442
be         2,022
made       2,081
through    2,083
file       5,371
info      18,558
##fl      10,258
correction  18,140
##key     14,839
=          1,027
tx        19,067
a          1,037
do         2,079
not        2,025
edit      10,086
changes    3,431
must       2,442
be         2,022
made       2,081
through    2,083
file       5,371
info      18,558
##fl      10,258
correction  18,140
##key     14,839
=          1,027
tx        19,067
a          1,037
5          1,019
##re       2,890
_          1,035
se         7,367
_          1,035
m1        23,290
_          1,035
km         2,463
.          1,012
ind       27,427
##d        2,094
14         2,403
2          1,016
/          1,013
26         2,656
/          1,013
2018       2,760
5          1,019
36         4,029
29         2,756
am         2,572
make       2,191
life       2,166
easier     6,082
entertain  20,432
people     2,111
15         2,321
do         2,079
not        2,025
edit      10,086
changes    3,431
must       2,442
be         2,022
made       2,081
through    2,083
file       5,371
info      18,558
##fl      10,258
correction  18,140
##key     14,839
=          1,027
tx        19,067
a          1,037
5          1,019
##re       2,890
_          1,035
se         7,367
_          1,035
m1        23,290
_          1,035
km         2,463
.          1,012
ind       27,427
##d        2,094
15         2,321
2          1,016
/          1,013
26         2,656
/          1,013
2018       2,760
5          1,019
36         4,029
30         2,382
am         2,572
inventor  12,235
##s        2,015
at         2,012
work       2,147
15         2,321
do         2,079
not        2,025
edit      10,086
changes    3,431
must       2,442
be         2,022
made       2,081
through    2,083
file       5,371
info      18,558
##fl      10,258
correction  18,140
##key     14,839
=          1,027
tx        19,067
a          1,037
[SEP]        102

In [18]:
#first occurence of [SEP] token
sep_idx = input_ids.index(tokenizer.sep_token_id)
print("SEP token index: ", sep_idx)
#number of tokens in segment A (question) - this will be one more than the sep_idx as the index in Python starts from 0
num_seg_a = sep_idx+1
print("Number of tokens in segment A: ", num_seg_a)
#number of tokens in segment B (text)
num_seg_b = len(input_ids) - num_seg_a
print("Number of tokens in segment B: ", num_seg_b)
#creating the segment ids
segment_ids = [0]*num_seg_a + [1]*num_seg_b
#making sure that every input token has a segment id
assert len(segment_ids) == len(input_ids)

SEP token index:  28
Number of tokens in segment A:  29
Number of tokens in segment B:  129

In [115]:
#token input_ids to represent the input and token segment_ids to differentiate our segments - question and text
output = model(torch.tensor([input_ids]),  token_type_ids=torch.tensor([segment_ids]))

In [172]:
output[1]

tensor([[-2.4156, -6.6629, -6.8642, -5.9544, -8.3814, -8.0438, -8.0945, -7.9225,
         -8.0399, -7.7815, -7.2786, -4.7019, -8.1204, -5.0698, -6.8717, -6.0148,
         -7.8503, -7.1352, -7.1254, -8.2480, -5.4543, -7.9040, -7.4123, -5.1981,
         -7.4550, -8.0987, -5.1727, -6.3818, -2.4155, -5.4693, -6.9212, -7.2936,
         -4.9880, -6.9921, -4.8580, -6.7075, -5.0784, -7.7436, -3.6239, -3.2122,
         -7.4189, -6.8947, -5.5579, -4.6956, -7.5091, -8.4032, -6.9668, -6.8079,
         -4.9824, -6.0465, -3.7021, -5.3140, -4.5458, -7.3114, -4.6758, -3.6578,
         -7.6674, -7.0563, -6.2493, -5.2202, -7.9281, -8.3795, -7.1799, -7.1211,
         -5.8065, -6.9560, -5.2882, -6.6323, -5.8026, -7.9397, -6.1841, -5.4330,
         -6.3662, -7.2274, -8.0478, -7.1627, -7.9148, -6.7986, -7.6810, -6.2359,
         -7.1530, -7.0377, -6.2035, -4.3262, -6.5550, -7.7008, -7.1185, -7.9403,
         -5.6137, -6.8120, -7.4580, -7.5331, -6.2718, -6.7208, -6.2827, -4.6122,
         -4.8429, -2.0622, -3.1469, -7.7078, -7.2427, -6.2168, -5.3903, -7.9701,
         -8.4362, -7.4289, -7.1749, -6.1863, -7.0424, -5.3345, -7.0263, -6.3801,
         -7.8868, -6.4533, -5.5935, -6.5627, -7.1821, -8.2548, -7.4378, -8.0747,
         -7.2741, -7.9148, -6.7424, -7.3838, -7.4137, -6.8868, -4.5613, -7.0344,
         -7.9631, -7.6489, -8.0693, -6.1438, -7.2976, -8.0429, -7.8571, -6.6239,
         -6.1440, -5.9509, -7.6123, -3.9555, -4.2273, -8.0926, -7.4065, -6.6365,
         -5.6784, -8.3259, -8.6346, -7.7678, -7.4838, -6.2748, -7.3174, -5.6976,
         -7.2243, -6.7114, -8.1379, -6.6487, -6.3242, -2.4157]],
       grad_fn=<SqueezeBackward1>)

In [174]:
#tokens with highest start and end scores ##### start_scores, end_scores
answer_start = torch.argmax(output.start_logits,dim=1)
answer_end = torch.argmax(output.end_logits,dim=1)
if answer_end >= answer_start:
    answer = " ".join(tokens[answer_start:answer_end+1])
else:
    print("I am unable to find the answer to this question. Can you please ask another question?")
    
print("\nQuestion:\n{}".format(question.capitalize()))
print("\nAnswer:\n{}.".format(answer.capitalize()))

Question:
Where was the auction held?

Answer:
Make life easier entertain people.

In [128]:
start_scores = answer_start
end_scores = answer_end

In [143]:
start_scores

tensor(93)

In [144]:
end_scores

tensor(97)

In [158]:
answer_start =start_scores.clone().detach()
answer_end = end_scores.clone().detach()

In [ ]:
start_pred = torch.argmax(outputs['start_logits'], dim=1)
end_pred = torch.argmax(outputs['end_logits'], dim=1)

In [170]:
start_scores.clone().detach().requires_grad_(True)

RuntimeError: only Tensors of floating point dtype can require gradients

In [168]:
answer_start

tensor(93)

In [179]:
## Find the tokens with the highest `start` and `end` scores.
#answer_start = torch.argmax(torch.tensor(start_scores))
answer_start =start_scores.clone().detach()
#answer_end = torch.argmax(end_scores)
answer_end = end_scores.clone().detach()
# Combine the tokens in the answer and print it out.
answer = " ".join(tokens[answer_start:answer_end+1])

print('Answer: "' + answer + '"')

Answer: "make life easier entertain people"

In [180]:
# it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True)

In [181]:
answer = tokens[answer_start]
for i in range(answer_start+1, answer_end+1):
    if tokens[i][0:2] == "##":
        answer += tokens[i][2:]
    else:
        answer += " " + tokens[i]

In [197]:
answer

'make life easier entertain people'

In [198]:
tokens

['[CLS]',
 'how',
 'to',
 'identify',
 'an',
 'information',
 '##al',
 'text',
 "'",
 's',
 'intended',
 'audience',
 'while',
 'reading',
 'and',
 'analyze',
 'how',
 'it',
 'affects',
 'the',
 'author',
 "'",
 's',
 'development',
 'of',
 'a',
 'text',
 '?',
 '[SEP]',
 'reasons',
 'to',
 'in',
 '##vent',
 'solve',
 'problems',
 'achieve',
 'fame',
 'and',
 'fortune',
 '14',
 'do',
 'not',
 'edit',
 'changes',
 'must',
 'be',
 'made',
 'through',
 'file',
 'info',
 '##fl',
 'correction',
 '##key',
 '=',
 'tx',
 'a',
 'do',
 'not',
 'edit',
 'changes',
 'must',
 'be',
 'made',
 'through',
 'file',
 'info',
 '##fl',
 'correction',
 '##key',
 '=',
 'tx',
 'a',
 '5',
 '##re',
 '_',
 'se',
 '_',
 'm1',
 '_',
 'km',
 '.',
 'ind',
 '##d',
 '14',
 '2',
 '/',
 '26',
 '/',
 '2018',
 '5',
 '36',
 '29',
 'am',
 'make',
 'life',
 'easier',
 'entertain',
 'people',
 '15',
 'do',
 'not',
 'edit',
 'changes',
 'must',
 'be',
 'made',
 'through',
 'file',
 'info',
 '##fl',
 'correction',
 '##key',
 '=',
 'tx',
 'a',
 '5',
 '##re',
 '_',
 'se',
 '_',
 'm1',
 '_',
 'km',
 '.',
 'ind',
 '##d',
 '15',
 '2',
 '/',
 '26',
 '/',
 '2018',
 '5',
 '36',
 '30',
 'am',
 'inventor',
 '##s',
 'at',
 'work',
 '15',
 'do',
 'not',
 'edit',
 'changes',
 'must',
 'be',
 'made',
 'through',
 'file',
 'info',
 '##fl',
 'correction',
 '##key',
 '=',
 'tx',
 'a',
 '[SEP]']

In [199]:
answer = tokens[answer_start]
answer

'make'

In [200]:
tokens[i][2:]

'EP]'

In [201]:
tokens[i][0:2]

'[S'

In [182]:
# Start with the first token.
answer = tokens[answer_start]

# Select the remaining answer tokens and join them with whitespace.
for i in range(answer_start + 1, answer_end + 1):
    
    # If it's a subword token, then recombine it with the previous token.
    if tokens[i][0:2] == '##':
        answer += tokens[i][2:]
    
    # Otherwise, add a space then the token.
    else:
        answer += ' ' + tokens[i]

print('Answer: "' + answer + '"')

Answer: "make life easier entertain people"

In [183]:
import matplotlib.pyplot as plt
import seaborn as sns

# Use plot styling from seaborn.
sns.set(style='darkgrid')

# Increase the plot size and font size.
#sns.set(font_scale=1.5)
plt.rcParams["figure.figsize"] = (16,8)

In [190]:
# Pull the scores out of PyTorch Tensors and convert them to 1D numpy arrays.
s_scores = answer_start.detach().numpy().flatten()
e_scores = answer_end.detach().numpy().flatten()

# We'll use the tokens as the x-axis labels. In order to do that, they all need
# to be unique, so we'll add the token index to the end of each one.
token_labels = []
for (i, token) in enumerate(tokens):
    token_labels.append('{:} - {:>0}'.format(token, i))

In [196]:
# Pull the scores out of PyTorch Tensors and convert them to 1D numpy arrays.
s_scores = answer_start.torch.tensor().numpy().flatten()
e_scores = answer_end.torch.tensor().numpy().flatten()

# We'll use the tokens as the x-axis labels. In order to do that, they all need
# to be unique, so we'll add the token index to the end of each one.
token_labels = []
for (i, token) in enumerate(tokens):
    token_labels.append('{:} - {:>0}'.format(token, i))

AttributeError: 'Tensor' object has no attribute 'torch'

In [194]:
e_scores

array([97])

In [191]:
token_labels

['[CLS] - 0',
 'how - 1',
 'to - 2',
 'identify - 3',
 'an - 4',
 'information - 5',
 '##al - 6',
 'text - 7',
 "' - 8",
 's - 9',
 'intended - 10',
 'audience - 11',
 'while - 12',
 'reading - 13',
 'and - 14',
 'analyze - 15',
 'how - 16',
 'it - 17',
 'affects - 18',
 'the - 19',
 'author - 20',
 "' - 21",
 's - 22',
 'development - 23',
 'of - 24',
 'a - 25',
 'text - 26',
 '? - 27',
 '[SEP] - 28',
 'reasons - 29',
 'to - 30',
 'in - 31',
 '##vent - 32',
 'solve - 33',
 'problems - 34',
 'achieve - 35',
 'fame - 36',
 'and - 37',
 'fortune - 38',
 '14 - 39',
 'do - 40',
 'not - 41',
 'edit - 42',
 'changes - 43',
 'must - 44',
 'be - 45',
 'made - 46',
 'through - 47',
 'file - 48',
 'info - 49',
 '##fl - 50',
 'correction - 51',
 '##key - 52',
 '= - 53',
 'tx - 54',
 'a - 55',
 'do - 56',
 'not - 57',
 'edit - 58',
 'changes - 59',
 'must - 60',
 'be - 61',
 'made - 62',
 'through - 63',
 'file - 64',
 'info - 65',
 '##fl - 66',
 'correction - 67',
 '##key - 68',
 '= - 69',
 'tx - 70',
 'a - 71',
 '5 - 72',
 '##re - 73',
 '_ - 74',
 'se - 75',
 '_ - 76',
 'm1 - 77',
 '_ - 78',
 'km - 79',
 '. - 80',
 'ind - 81',
 '##d - 82',
 '14 - 83',
 '2 - 84',
 '/ - 85',
 '26 - 86',
 '/ - 87',
 '2018 - 88',
 '5 - 89',
 '36 - 90',
 '29 - 91',
 'am - 92',
 'make - 93',
 'life - 94',
 'easier - 95',
 'entertain - 96',
 'people - 97',
 '15 - 98',
 'do - 99',
 'not - 100',
 'edit - 101',
 'changes - 102',
 'must - 103',
 'be - 104',
 'made - 105',
 'through - 106',
 'file - 107',
 'info - 108',
 '##fl - 109',
 'correction - 110',
 '##key - 111',
 '= - 112',
 'tx - 113',
 'a - 114',
 '5 - 115',
 '##re - 116',
 '_ - 117',
 'se - 118',
 '_ - 119',
 'm1 - 120',
 '_ - 121',
 'km - 122',
 '. - 123',
 'ind - 124',
 '##d - 125',
 '15 - 126',
 '2 - 127',
 '/ - 128',
 '26 - 129',
 '/ - 130',
 '2018 - 131',
 '5 - 132',
 '36 - 133',
 '30 - 134',
 'am - 135',
 'inventor - 136',
 '##s - 137',
 'at - 138',
 'work - 139',
 '15 - 140',
 'do - 141',
 'not - 142',
 'edit - 143',
 'changes - 144',
 'must - 145',
 'be - 146',
 'made - 147',
 'through - 148',
 'file - 149',
 'info - 150',
 '##fl - 151',
 'correction - 152',
 '##key - 153',
 '= - 154',
 'tx - 155',
 'a - 156',
 '[SEP] - 157']

In [185]:
s_scores

array([93])

In [193]:
# Create a barplot showing the start word score for all of the tokens.
ax = sns.barplot(x=token_labels, y=s_scores, ci=None)

# Turn the xlabels vertical.
ax.set_xticklabels(ax.get_xticklabels(), rotation=90, ha="center")

# Turn on the vertical grid to help align words to scores.
ax.grid(True)

plt.title('Start Word Scores')

plt.show()

KeyError: '[CLS] - 0'

In [135]:
def question_answer(question, text):
    
    #tokenize question and text as a pair
    input_ids = tokenizer.encode(question, text)
    
    #string version of tokenized ids
    tokens = tokenizer.convert_ids_to_tokens(input_ids)
    
    #segment IDs
    #first occurence of [SEP] token
    sep_idx = input_ids.index(tokenizer.sep_token_id)
    #number of tokens in segment A (question)
    num_seg_a = sep_idx+1
    #number of tokens in segment B (text)
    num_seg_b = len(input_ids) - num_seg_a
    
    #list of 0s and 1s for segment embeddings
    segment_ids = [0]*num_seg_a + [1]*num_seg_b
    assert len(segment_ids) == len(input_ids)
    
    #model output using input_ids and segment_ids
    output = model(torch.tensor([input_ids]), token_type_ids=torch.tensor([segment_ids]))
    
    #reconstructing the answer
    answer_start = torch.argmax(output.start_logits)
    answer_end = torch.argmax(output.end_logits)
    if answer_end >= answer_start:
        answer = tokens[answer_start]
        for i in range(answer_start+1, answer_end+1):
            if tokens[i][0:2] == "##":
                answer += tokens[i][2:]
            else:
                answer += " " + tokens[i]
                
    if answer.startswith("[CLS]"):
        answer = "Unable to find the answer to your question."
    
    print("\nPredicted answer:\n{}".format(answer.capitalize()))

In [136]:
text = """New York (CNN) -- More than 80 Michael Jackson collectibles -- including the late pop star's famous rhinestone-studded glove from a 1983 performance -- were auctioned off Saturday, reaping a total $2 million. Profits from the auction at the Hard Rock Cafe in New York's Times Square crushed pre-sale expectations of only $120,000 in sales. The highly prized memorabilia, which included items spanning the many stages of Jackson's career, came from more than 30 fans, associates and family members, who contacted Julien's Auctions to sell their gifts and mementos of the singer. Jackson's flashy glove was the big-ticket item of the night, fetching $420,000 from a buyer in Hong Kong, China. Jackson wore the glove at a 1983 performance during \"Motown 25,\" an NBC special where he debuted his revolutionary moonwalk. Fellow Motown star Walter \"Clyde\" Orange of the Commodores, who also performed in the special 26 years ago, said he asked for Jackson's autograph at the time, but Jackson gave him the glove instead. "The legacy that [Jackson] left behind is bigger than life for me,\" Orange said. \"I hope that through that glove people can see what he was trying to say in his music and what he said in his music.\" Orange said he plans to give a portion of the proceeds to charity. Hoffman Ma, who bought the glove on behalf of Ponte 16 Resort in Macau, paid a 25 percent buyer's premium, which was tacked onto all final sales over $50,000. Winners of items less than $50,000 paid a 20 percent premium."""
question = "Where was the Auction held?"
question_answer(question, text)
#original answer from the dataset
print("Original answer:\n", data.loc[data["question"] == question]["answer"].values[0])

Predicted answer:
Hard rock cafe in new york ' s times square
Original answer:
 Hard Rock Cafe

In [139]:
text = input("Please enter your text: \n")
question = input("\nPlease enter your question: \n")
while True:
    question_answer(question, text)
    
    flag = True
    flag_N = False
    
    while flag:
        response = input("\nDo you want to ask another question based on this text (Y/N)? ")
        if response[0] == "Y":
            question = input("\nPlease enter your question: \n")
            flag = False
        elif response[0] == "N":
            print("\nBye!")
            flag = False
            flag_N = True
            
    if flag_N == True:
        break

KeyboardInterrupt: Interrupted by user

___
# 1. Install huggingface transformers library

In [ ]:
#!pip install transformers

In [1]:
import torch

___
# 2. Load Fine-Tuned BERT-large

In [67]:
from transformers import BertForQuestionAnswering

model = BertForQuestionAnswering.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')

In [68]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')

___
# 3. Ask a Question

In [69]:
question = "How many parameters does BERT-large have?"
answer_text = "BERT-large is really big... it has 24-layers and an embedding size of 1,024, for a total of 340M parameters! Altogether it is 1.34GB, so expect it to take a couple minutes to download to your Colab instance."

In [70]:
# Apply the tokenizer to the input text, treating them as a text-pair.
input_ids = tokenizer.encode(question, answer_text)

print('The input has a total of {:} tokens.'.format(len(input_ids)))

The input has a total of 70 tokens.

In [71]:
input_ids

[101,
 2129,
 2116,
 11709,
 2515,
 14324,
 1011,
 2312,
 2031,
 1029,
 102,
 14324,
 1011,
 2312,
 2003,
 2428,
 2502,
 1012,
 1012,
 1012,
 2009,
 2038,
 2484,
 1011,
 9014,
 1998,
 2019,
 7861,
 8270,
 4667,
 2946,
 1997,
 1015,
 1010,
 6185,
 2549,
 1010,
 2005,
 1037,
 2561,
 1997,
 16029,
 2213,
 11709,
 999,
 10462,
 2009,
 2003,
 1015,
 1012,
 4090,
 18259,
 1010,
 2061,
 5987,
 2009,
 2000,
 2202,
 1037,
 3232,
 2781,
 2000,
 8816,
 2000,
 2115,
 15270,
 2497,
 6013,
 1012,
 102]

In [72]:
# BERT only needs the token IDs, but for the purpose of inspecting the 
# tokenizer's behavior, let's also get the token strings and display them.
tokens = tokenizer.convert_ids_to_tokens(input_ids)

# For each token and its id...
for token, id in zip(tokens, input_ids):
    
    # If this is the [SEP] token, add some space around it to make it stand out.
    if id == tokenizer.sep_token_id:
        print('')
    
    # Print the token string and its ID in two columns.
    print('{:<12} {:>6,}'.format(token, id))

    if id == tokenizer.sep_token_id:
        print('')

[CLS]           101
how           2,129
many          2,116
parameters   11,709
does          2,515
bert         14,324
-             1,011
large         2,312
have          2,031
?             1,029

[SEP]           102

bert         14,324
-             1,011
large         2,312
is            2,003
really        2,428
big           2,502
.             1,012
.             1,012
.             1,012
it            2,009
has           2,038
24            2,484
-             1,011
layers        9,014
and           1,998
an            2,019
em            7,861
##bed         8,270
##ding        4,667
size          2,946
of            1,997
1             1,015
,             1,010
02            6,185
##4           2,549
,             1,010
for           2,005
a             1,037
total         2,561
of            1,997
340          16,029
##m           2,213
parameters   11,709
!               999
altogether   10,462
it            2,009
is            2,003
1             1,015
.             1,012
34            4,090
##gb         18,259
,             1,010
so            2,061
expect        5,987
it            2,009
to            2,000
take          2,202
a             1,037
couple        3,232
minutes       2,781
to            2,000
download      8,816
to            2,000
your          2,115
cola         15,270
##b           2,497
instance      6,013
.             1,012

[SEP]           102

In [73]:
tokens

['[CLS]',
 'how',
 'many',
 'parameters',
 'does',
 'bert',
 '-',
 'large',
 'have',
 '?',
 '[SEP]',
 'bert',
 '-',
 'large',
 'is',
 'really',
 'big',
 '.',
 '.',
 '.',
 'it',
 'has',
 '24',
 '-',
 'layers',
 'and',
 'an',
 'em',
 '##bed',
 '##ding',
 'size',
 'of',
 '1',
 ',',
 '02',
 '##4',
 ',',
 'for',
 'a',
 'total',
 'of',
 '340',
 '##m',
 'parameters',
 '!',
 'altogether',
 'it',
 'is',
 '1',
 '.',
 '34',
 '##gb',
 ',',
 'so',
 'expect',
 'it',
 'to',
 'take',
 'a',
 'couple',
 'minutes',
 'to',
 'download',
 'to',
 'your',
 'cola',
 '##b',
 'instance',
 '.',
 '[SEP]']

In [74]:
# Search the input_ids for the first instance of the `[SEP]` token.
sep_index = input_ids.index(tokenizer.sep_token_id)

# The number of segment A tokens includes the [SEP] token istelf.
num_seg_a = sep_index + 1

# The remainder are segment B.
num_seg_b = len(input_ids) - num_seg_a

# Construct the list of 0s and 1s.
segment_ids = [0]*num_seg_a + [1]*num_seg_b

# There should be a segment_id for every input token.
assert len(segment_ids) == len(input_ids)

In [75]:
#from transformers import pipeline

In [76]:
#bert_qa = pipeline('question-answering',model =model,tokenizer=tokenizer)

In [77]:
import numpy as np
# Run our example through the model.
start_scores, end_scores = model(torch.tensor([input_ids]), # The tokens representing our input text.
                                token_type_ids=torch.tensor([segment_ids])) # The segment IDs to differentiate question from answer_text

In [78]:
end_scores

'end_logits'

In [79]:
torch.tensor([input_ids])

tensor([[  101,  2129,  2116, 11709,  2515, 14324,  1011,  2312,  2031,  1029,
           102, 14324,  1011,  2312,  2003,  2428,  2502,  1012,  1012,  1012,
          2009,  2038,  2484,  1011,  9014,  1998,  2019,  7861,  8270,  4667,
          2946,  1997,  1015,  1010,  6185,  2549,  1010,  2005,  1037,  2561,
          1997, 16029,  2213, 11709,   999, 10462,  2009,  2003,  1015,  1012,
          4090, 18259,  1010,  2061,  5987,  2009,  2000,  2202,  1037,  3232,
          2781,  2000,  8816,  2000,  2115, 15270,  2497,  6013,  1012,   102]])

In [80]:
torch.tensor([segment_ids])

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

____
# My Data

In [35]:
import pandas as pd


path = "/Users/kazotogbah/Desktop/CapstoneWritting/hmh_data/grade5_teachers_guide_pal_corpus_clean_keywords_sumy_distilroberta34b1dc07f9547647fb90760ba6630e5f92fd7af8e4a0d66a84cc084020f76b2d.pkl" 
teachersGuidePal = pd.read_pickle(path,compression='infer')
teachersGuidePal

,file,page,text,content_type,Skill Title,Skill Description,Skill GUID,Skill Code,strand,strand_description,...,Skill Title_embedded,Skill Description_embedded,strand_embedded,Skill Title_no_periods_embedded,Skill Description_no_periods_embedded,strand_no_periods_embedded,strand_description_no_periods_embedded,skill_description_keywords_embedded,strand_description_keywords_embedded,text_clean_summarized_embedded
0,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,1.0,MODULE\n˜\nﬁ I will not follow \nwhere the pat...,content,module i will not follow where the path may le...,module i will not follow where the path may le...,nan,nan,module i will not follow where the path may le...,module i will not follow where the path may le...,...,"[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.28464243, 0.2220484, 0.4422115, 0.0465012, ...","[0.28464243, 0.2220484, 0.4422115, 0.0465012, ...","[0.20862822, -0.033599023, 0.044862866, 0.2881..."
1,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,2.0,MODULE\n˜\nﬁ I will not follow \nwhere the pat...,content,module i will not follow where the path may le...,module i will not follow where the path may le...,nan,nan,module i will not follow where the path may le...,module i will not follow where the path may le...,...,"[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.05007931, 0.119613454, 0.032607853, 0.41877...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.021318758, 0.13580242, 0.051272195, 0.41786...","[0.30782643, 0.058543533, 0.16792017, 0.085862...","[0.30782643, 0.058543533, 0.16792017, 0.085862...","[0.16788949, -0.13963626, -0.07024216, 0.53562..."
2,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,3.0,˜˚˛˝˙ˆˇ˘˝\n\nˆˇ\nThe words in the chart will h...,content,the words in the chart will help you talk and ...,the words in the chart will help you talk and ...,nan,nan,the words in the chart will help you talk and ...,the words in the chart will help you talk and ...,...,"[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.318849, 0.5429922, 0.2398742, -0.08303005, ...","[0.318849, 0.5429922, 0.2398742, -0.08303005, ...","[0.23586863, 0.037411276, 0.0036898185, 0.0774..."
3,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,4.0,˜˚˛˝˙ˆˇ˘˝\n\nˆˇ\nThe words in the chart will h...,content,the words in the chart will help you talk and ...,the words in the chart will help you talk and ...,nan,nan,the words in the chart will help you talk and ...,the words in the chart will help you talk and ...,...,"[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.24913393, -0.16405915, -0.045558963, -0.163...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.2626564, -0.15431736, -0.14201987, -0.11405...","[0.34651068, 0.33815506, 0.31886512, -0.218285...","[0.34651068, 0.33815506, 0.31886512, -0.218285...","[0.13544446, 0.15687963, -0.033667527, -0.0243..."
4,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,5.0,˜\n˚˛˝˙˜\n\nReasons to \nInvent\nSolve \nProbl...,content,reasons to invent solve problems achieve fame ...,reasons to invent solve problems achieve fame ...,nan,nan,reasons to invent solve problems achieve fame ...,reasons to invent solve problems achieve fame ...,...,"[0.2885548, 0.023478366, 0.30554906, 0.3569067...","[0.2885548, 0.023478366, 0.30554906, 0.3569067...","[0.2885548, 0.023478366, 0.30554906, 0.3569067...","[0.2572909, 0.11252953, 0.25145745, 0.29272386...","[0.2572909, 0.11252953, 0.25145745, 0.29272386...","[0.2572909, 0.11252953, 0.25145745, 0.29272386...","[0.2572909, 0.11252953, 0.25145745, 0.29272386...","[0.21129978, 0.31341118, 0.3093127, 0.29272902...","[0.21129978, 0.31341118, 0.3093127, 0.29272902...","[0.27298772, 0.018115517, 0.27320105, 0.338362..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5577,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write haikus or tankas,write haikus or tankas following the structura...,e0653513-1af9-493c-99cc-ca26440a59cb,WT.WP.2.C4,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[-0.24465016, -0.41559923, -0.22348292, -0.189...","[-0.14750454, -0.020040585, -0.3024932, -0.139...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.24465016, -0.41559923, -0.22348292, -0.189...","[-0.14750454, -0.020040585, -0.3024932, -0.139...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.065458834, -0.022467336, -0.14402398, -0.1...","[-0.16295668, -0.059479393, -0.22297119, -0.04...","[0.15197246, -0.00865834, -0.2474561, -0.14950...","[-0.035868734, -0.07316666, -0.20177855, -0.15..."
5578,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write riddle poems,write riddle poems that require the reader to ...,97410ba5-9fc4-4684-97c4-9be529ceafe5,WT.WP.2.C5,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[-0.1577658, -0.096144654, -0.15173835, 0.1961...","[-0.2399435, -0.15688682, -0.09092543, -0.1290...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.1577658, -0.096144654, -0.15173835, 0.1961...","[-0.2399435, -0.15688682, -0.09092543, -0.1290...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.14212829, -0.087659754, 0.0151685495, -0.1...","[-0.2681789, -0.12879677, 0.017346552, -0.3627...","[0.05806018, 0.06841876, -0.053806134, -0.1370...","[-0.08528366, -0.17463017, -0.021595858, -0.16..."
5579,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write odes,write odes to praise people events objects or ...,d5d3e7af-d5b5-45f9-8320-77db880d3856,WT.WP.2.C6,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[0.22441971, -0.30364242, 0.34133807, -0.45593...","[0.38578078, 0.07033281, 0.098516926, -0.27138...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[0.22441971, -0.30364242, 0.34133807, -0.45593...","[0.38578078, 0.07033281, 0.098516926, -0.27138...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[0.016466925, -0.037565004, 0.065129966, -0.15...","[0.48021975, -0.18707027, -0.0040784995, 0.037...","[0.27416033, 0.013461181, 0.005883138, -0.0807...","[0.05119294, -0.12402764, 0.02975093, -0.16433..."
5580,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write sonnets,write sonnets following the structural charact...,7637f149-07f8-4ca0-84d7-5593e1b9211a,WT.WP.2.C7,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[-0.3031502, 0.4306519, 0.087189816, 0.1234787...","[-0.21402566, 0.4978751, -0.04160893, 0.137464...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.3031502, 0.4306519, 0.087189816, 0.1234787...","[-0.21402566, 0.4978751, -0.04160893, 0.137464...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.1443302, 0.115797274, 0.0013336517, 0.0579...","[-0.11399182, 0.3713151, -0.121542305, 0.20513...","[0.14028896, 0.2253419, -0.05671437, 0.1401694...","[-0.10235442, 0.053097203, -0.021812407, 0.012..."
5581,C:\Users\rdominguez\Documents\Pers\UChicago\Ca...,nan,nan,skill,write free verse poems,write poems in free verse that depart from tra...,d774010e-382b-417f-842b-21dcc46a5a65,WT.WP.2.C8,writing researching producing and presenting w...,writing researching producing and presenting w...,...,"[-0.26282188, -0.2267464, 0.063811034, -0.3585...","[-0.14395787, 0.20046626, 0.066164464, -0.3402...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.26282188, -0.2267464, 0.063811034, -0.3585...","[-0.14395787, 0.20046626, 0.066164464, -0.3402...","[0.11302414, -0.017285429, 0.070959605, -0.008...","[-0.1202832, 0.020569142, 0.08610445, -0.27497...","[0.1200044, 0.022991914, 0.19192894, -0.269595...","[0.19046833, 0.14302915, -0.020604758, -0.1473...","[-0.047682863, -0.05864437, 0.059854243, -0.29..."

In [36]:
## collect page content and skill description
import pandas as pd
import numpy as np
pal_skills2 = []
pal_content2 = []
page = -1
for text in teachersGuidePal['content_type']:
    page = page+1
    if teachersGuidePal['content_type'][page]== "content":
        pal_content2.append(teachersGuidePal['Skill Description'][page])
    else:
        pal_skills2.append(teachersGuidePal['Skill Description'][page])

In [37]:
# concatenate question question words
import pandas as pd
import numpy as np
skills_to_Quest = []
skillnum = -1
concat_1 = "How to "
concat_2 = "?"
for skill in pal_skills2:
    skillnum = skillnum+1
    skills_to_Quest.append(concat_1 + pal_skills2[skillnum] + concat_2)
    
skills_to_Quest

["How to identify an informational text's intended audience while reading and analyze how it affects the author's development of a text?",
 "How to understand that authors write texts for different purposes to inform persuade entertain or share thoughts or feelings and identify author's purpose(s) while reading text?",
 'How to while reading analyze how the author advances the purpose of a text in terms of style and use of text structure language and rhetoric (e.g. formal or informal language figures of speech tone persuasiveness) and evaluate the degree to which the author achieved the purpose of the text?',
 "How to determine the author's perspective and opinions including underlying values and beliefs based on explicit and implicit information while reading text?",
 "How to identify and analyze an author's qualifications to evaluate the author's credibility?",
 "How to while reading evaluate how an author's personal cultural and historical background impacts their purpose for writing and the structure and meaning of a text?",
 "How to distinguish the author's opinions from one's own opinions while reading text?",
 "How to while reading identify an author's opinions beliefs and attitudes that bias text based on explicit and implicit information from the text or information about the author's background?",
 "How to evaluate how an author's perspective or opinions impact a text while reading?",
 "How to while reading compare and contrast how different authors' personal cultural and historical backgrounds impact their purpose for writing and the structure and meaning of the texts they write?",
 "How to identify the author's purpose in individual paragraphs or sections of a text?",
 'How to set a purpose for reading text?',
 "How to preview the text to gain information about a text's author genre topic and structure creating a context to inform the text's meaning and significance while reading?",
 'How to make and confirm or refute predictions while reading in order to engage with a text and deepen comprehension?',
 "How to make personal connections between a text and one's own experiences feelings and perspectives to actively read and comprehend deeply?",
 'How to connect a text to what is known about the world and the way things are outside the self to actively read and comprehend deeply?',
 'How to connect information between texts during or after reading to aid with comprehending the new text and to broaden knowledge and gain new perspectives?',
 "How to ask and answer questions while reading to help clarify comprehension deepen understanding of a text's literal meaning and demonstrate comprehension?",
 'How to ask and answer interpretive and evaluative questions while reading to support comprehension and analysis of a text and demonstrate comprehension?',
 'How to visualize situations while reading to develop a deeper understanding and enhance recall of the text?',
 'How to use graphic organizers to aid in comprehension and analysis of text while reading or for later use?',
 'How to use note taking and annotation strategies while reading to monitor comprehension of text or for later use?',
 'How to while reading periodically check for coherence and understanding of main ideas events and concepts?',
 'How to when comprehension breaks down during reading use strategies to adjust such as rereading adjusting reading rate reading ahead summarizing or questioning difficult parts of the text?',
 "How to combine information gained from reading a text with one's own academic and personal knowledge to make inferences about what is not stated directly?",
 'How to distinguish between works of fiction and nonfiction while reading based on text content and features?',
 'How to choose texts for independent reading based on personal preferences of topics authors and genres or reviews or recommendations?',
 'How to access prior knowledge to support comprehension and evaluation of a text while reading?',
 'How to adjust reading style (e.g. skimming re reading close reading) based on purpose for reading?',
 'How to build background knowledge to support comprehension and evaluation of a text while reading?',
 'How to while reading distinguish true realistic and fantastical literary works and elements of literary works?',
 'How to generalize information gained from reading a text to make a prediction about a related situation or text?',
 'How to distinguish between literary and informational texts while reading?',
 'How to evaluate the plausibility of predictions about text based on text evidence while reading?',
 'How to draw conclusions from reading text based on a combination of information from the text and background knowledge to make decisions arrive at opinions or determine results?',
 'How to use a combination of information from text and background knowledge to make valid generalizations about a subject based on reading?',
 'How to cite text details examples and evidence from reading to support inferences conclusions interpretations and arguments?',
 'How to engage in classroom small group or partner conversations about the text during and after reading to build on thoughts and ideas and to deepen understanding of the text?',
 'How to write a response to text after reading to share thoughts feelings ideas or opinions about what was read to aid recall or to deepen comprehension?',
 'How to respond to a text after reading by creating an illustration that recounts events ideas and details about the text?',
 'How to while reading analyze the connections relationships or interactions between individuals ideas or events in a text and explain how they develop throughout the course of the text?',
 'How to while reading compare and contrast works of fiction to works of nonfiction that are about the same or similar topic events or people?',
 "How to while reading analyze how a selection from a text fits into the overall structure of the text and contributes to the text's development?",
 'How to while reading evaluate the degree to which the meaning of a text is clear or ambiguous and the information in a text is consistent or inconsistent and determine the impact on the meaning and significance of the text?',
 'How to evaluate how different mediums present the same text or topic (e.g. books oral performances presentations films) and evaluate similarities and differences in how each medium interprets or represents it?',
 'How to distinguish between an objective summary and a critique or review of text?',
 'How to evaluate summaries of text for accuracy meaning or objectivity?',
 'How to compare and contrast the structure and organization of two or more informational texts while reading?',
 'How to synthesize ideas from reading texts across genres to draw conclusions about the texts and develop knowledge?',
 'How to reflect and respond from a personal perspective (e.g. level of personal enjoyment what was learned agreement/disagreement) after reading text?',
 'How to evaluate the quality and relevance of evidence from text when citing evidence to support inferences conclusions interpretations and arguments?',
 "How to paraphrase texts or parts of texts in one's own words after reading retaining the meaning structure and order of the text?",
 'How to synthesize ideas from different parts within a text while reading to understand how the ideas fit together and contribute to the overall significance of the text?',
 'How to synthesize ideas from written texts with texts read aloud and/or media to draw conclusions and develop knowledge?',
 'How to summarize texts objectively after reading providing a shortened version of the text that retains the main points?',
 'How to orally summarize texts objectively after reading providing a shortened version of the text that retains the main points?',
 'How to write objective summaries of text after reading providing a shortened version of the text that retains the main points?',
 'How to collaborate to produce writing or media after reading text?',
 "How to understand that graphic features such as illustrations maps or charts contribute to a text's meaning and identify interpret and use graphic features while reading?",
 'How to while reading evaluate the degree to which the graphic features in a text contribute important information that cannot be conveyed by the words alone?',
 'How to understand that text features including chapters headings sub headings and bullets are used to provide organization and visual interest to a text and identify interpret and use text features to locate information while reading text?',
 'How to evaluate the degree to which text features support comprehension while reading text?',
 'How to synthesize information from multiple graphic features to draw conclusions while reading text?',
 'How to understand that information is provided by graphic features and by words and distinguish information that is provided by graphics and by words while reading text?',
 'How to integrate information from text features and/or graphic features to comprehend text while reading?',
 "How to understand that imagery consists of words that appeal to readers' senses and identify imagery while reading text?",
 'How to understand that parallelism is a repetition of grammatically identical words or phrases in a sentence to give it a balance and rhythm and identify parallelism while reading text?',
 "How to while reading text evaluate the degree to which parallelism provides balance and rhythm to a sentence and supports the author's purpose?",
 'How to understand that dialogue is a conversation between two or more characters and identify dialogue while reading text?',
 'How to understand that a dialect is the way a group of people speak a language based on location or background and that authors use dialect to help define characters and identify the use of dialects while reading text?',
 'How to while reading text evaluate the degree to which use of dialects helps define characters?',
 'How to understand that register is the degree of formality in language and identify register while reading text?',
 'How to while reading evaluate the degree to which use of register helps define characters and sets the tone of a work of literature?',
 'How to understand that mood is the emotional atmosphere conveyed by an author and identify the mood of a text while reading?',
 "How to while reading analyze the details that helped create a text's mood and evaluate their effectiveness?",
 "How to understand that tone conveys an author's attitudes and viewpoints toward the topic of the literary work and identify the tone of a text while reading?",
 "How to while reading analyze an author's tone or attitude toward a topic and identify details that communicate the tone?",
 "How to understand that an author's style is the overall voice of the author based on use of language and literary devices to give the work meaning and describe authors' styles while reading?",
 'How to while reading classical and modern works of literature identify and compare and contrast archetypes?',
 'How to while reading classical and modern works of literature identify and compare and contrast motifs?',
 'How to understand that language can be used literally and figuratively and identify literal and figurative uses of language while reading text?',
 "How to while reading analyze the use of figurative language for imagery or rhetorical effect and evaluate its impact on a text and the degree to which it advances the author's purpose?",
 "How to while reading text analyze how use of idioms impacts tone and advances the author's purpose?",
 'How to understand that oxymorons are combinations of words with contrasting meanings and that paradoxes are combinations of self contradictory statements and identify oxymorons and paradoxes while reading?',
 "How to while reading text analyze how use of contradictory language including oxymorons and paradoxes impacts tone and advances the author's purpose in a text?",
 "How to while reading text analyze author's use of literary devices to determine how they impact a text and the degree to which they achieve their purposes?",
 'How to understand that an anecdote is a very short story about an incident that can add meaning interest and informal evidence to a text or dialogue through qualities such as humor inspiration or a personal memory and identify anecdotes while reading text?',
 'How to evaluate the degree to which anecdotes achieve their purpose while reading text?',
 'How to understand that stereotyping is the attribution of a trait or traits to all members of a group rather than treating group members as individuals with many different traits and identify examples of stereotyping while reading text?',
 "How to analyze examples of imagery while reading text to determine which senses they appeal to and the degree to which they add to the reader's experience?",
 "How to while reading text evaluate the degree to which stereotyping impacts the text's development?",
 "How to while reading text analyze an author's use of euphemisms and evaluate how they are used to soften the author's message?",
 "How to understand that euphemisms are words or phrases that are more polite or indirect and used to soften another word or phrase or to neutralize a word's connotation and identify and interpret euphemisms while reading text?",
 "How to while reading text analyze an author's voice or style to understand the author's attitude and evaluate the impact of voice on the meaning the text?",
 "How to while reading text analyze how use of puns impacts tone and advances the author's purpose?",
 'How to understand that sound devices use patterns of sound repetition or words that suggest sounds to impact the meaning and mood of writing and identify sound devices such as assonance consonance alliteration or onomatopoeia while reading text?',
 'How to while reading text evaluate how use of sound devices impacts the meaning and mood of the text and enhances its aesthetic qualities?',
 "How to while reading compare and contrast different authors' use of literary devices to determine how they impact the texts and the degree to which they achieve their purposes?",
 'How to understand that idioms are phrases that have a specific meaning different from their literal meaning and identify idioms while reading text?',
 'How to understand that authors repeat words and phrases for emphasis and identify repetition in while reading text?',
 'How to understand that proverbs and adages are phrases that communicate general truths or advice that go beyond their literal meaning and identify proverbs and adages while reading text?',
 'How to understand that extended metaphors are figurative comparisons developed at length throughout literary works and identify examples of extended metaphors while reading text?',
 'How to while reading text analyze the meaning of extended metaphors and the degree to which they achieve their purpose?',
 'How to understand that similes and metaphors draw comparisons between two different ideas or things but that similes use "like" or "as" to draw the comparison and metaphors do not and identify similes and metaphors while reading text?',
 'How to while reading text analyze the purposes of similes and metaphors and the degree to which they achieve their purposes?',
 'How to understand that analogies use similes and metaphors to compare two very different things and identify analogies while reading text?',
 'How to while reading text analyze the effects that analogies have on the meaning of what they compare?',
 'How to understand that personification attributes human qualities to animals ideas and objects and identify personification while reading text?',
 "How to while reading text analyze examples of personification and evaluate how they affect the readers' perspective of the object of personification?",
 'How to understand that a symbol is an object that represents something else and gives it a special and deeper meaning and identify symbols and interpret what they represent while reading text?',
 "How to while reading text analyze why an author used symbols and how the symbols added to the reader's understanding of the text?",
 'How to understand that allegories are narratives told on literal and symbolic levels in order to communicate about abstract ideas and identify examples of allegories while reading text?',
 'How to while reading text analyze the meanings of the symbolism found in allegories and evaluate their effectiveness in communicating the message of the text?',
 'How to understand that an allusion is a short indirect reference to a person or thing that has a particular significance (e.g. cultural historical) and identify allusions while reading text?',
 'How to evaluate the degree to which an allusion achieves its purpose in a text while reading?',
 'How to understand that irony uses language to convey a message that is different from its literal meaning and identify and interpret irony while reading text?',
 'How to understand the similarities and differences between verbal situational and dramatic irony and identify each type while reading?',
 'How to while reading evaluate the degree to which irony deepens understanding of and adds interest to text?',
 'How to understand that sarcasm uses ironic language to mock insult or convey contempt and identify and interpret sarcasm while reading text?',
 'How to while reading text evaluate the degree to which sarcasm deepens understanding of and adds interest?',
 'How to understand that hyperbole is an extreme exaggeration to emphasize a point or for dramatic effect and identify hyperbole while reading text?',
 "How to while reading text evaluate the degree to which hyperbole emphasizes points and impacts the reader's interest?",
 "How to understand that satire is a device that points out a person's or group's negative qualities by using humor exaggeration and irony for the purpose of exposing those qualities and identify examples of satire while reading?",
 'How to while reading evaluate the degree to which satirical texts achieve their purpose?',
 "How to while reading text evaluate the degree to which an author's word choices are clear accurate and appropriate to convey the author's message effectively?",
 'How to identify the topic that the author addresses in a informational text while reading?',
 'How to identify text level main ideas in informational texts while reading?',
 'How to identify paragraph or section level main ideas in informational text while reading?',
 'How to while reading identify key details that support the main ideas of texts paragraphs or sections of text?',
 'How to identify and analyze conflicting information across two or more informational texts while reading?',
 'How to while reading informational text analyze the development of main ideas and the use of key details to support them?',
 'How to identify paragraph or section level topics in informational texts while reading?',
 'How to while reading evaluate the importance and relevance of key details that support the main ideas of informational texts paragraphs or sections of text?',
 "How to understand that scope is a text's coverage of a topic which can range from narrow (covering few details related to a topic) to broad (covering many details related to a topic) and identify the scope of informational texts while reading?",
 'How to identify individuals ideas concepts or events in informational texts while reading?',
 'How to identify sequential or chronological order of events or steps in a process in informational text while reading using signal words and clues as aids (e.g. now then once already before during after and then and dates [days months years])?',

In [38]:
contexts=[]
questions = []
for i in range(10):
    questions.append(skills_to_Quest[i])
    contexts.append(pal_content2[i])
    i=i+1

questions[9]

"How to while reading compare and contrast how different authors' personal cultural and historical backgrounds impact their purpose for writing and the structure and meaning of the texts they write?"

In [39]:
contexts[0]

"module i will not follow where the path may lead but i will go where there is no path and i will leave a trail.fl smuriel strode inventors at work inventors at work 10 do not edit changes must be made through file infofl correctionkey=tx a do not edit changes must be made through file infofl correctionkey=tx a 5re_se_m1_mo.indd 10 2/26/2018 5 35 52 am what kinds of circumstances push people to create new inventions? 11 do not edit changes must be made through file infofl correctionkey=tx b nl b 5re_se_m1_mo.indd 11 11/2/2018 12 53 07 am introduce the topic read aloud the module title inventors at work. tell students that in this module they will be reading and viewing selections on the topic of inventors. have students brainstorm famous inventors and share what they know about their inventions. then ask students to discuss the module title and explain the different types of work inventors may do to come up with an invention that works. (possible responses inventors do a lot of research. they also have to test out their ideas and problem solve when something doesn t work.) discuss the quotation read aloud the quotation by muriel strode. lead a discussion in which students discuss whether they agree with strode's statement and why. explain the meaning of the quote as needed inventors strive to discover new paths or new ways of doing things. give examples of recent inventions that have made our lives better. (accept reasonable responses.) 10 module 1 do not edit changes must be made through file infofl correctionkey=tx b nl b"

---
# my Model

In [40]:
## distilBert Q&A
from transformers import DistilBertTokenizer, DistilBertForQuestionAnswering
import torch

distil_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased',return_token_type_ids = True)
distil_model = DistilBertForQuestionAnswering.from_pretrained('distilbert-base-uncased-distilled-squad')

In [41]:
from transformers import pipeline 
distil_bert_qa = pipeline('question-answering',model =distil_model,tokenizer=distil_tokenizer)

In [ ]:
start_scores, end_scores = distil_bert_qa()

In [ ]:
encoded_dict = tokenizer.encode_plus(text=question,
text_pair=answer_text, add_special=True)

token_type_ids = encoded_dict['token_type_ids']

___

In [131]:
# Find the tokens with the highest `start` and `end` scores.
answer_start = torch.argmax(torch.tensor(start_scores))
answer_end = torch.argmax(end_scores)

# Combine the tokens in the answer and print it out.
answer = ' '.join(tokens[answer_start:answer_end+1])

print('Answer: "' + answer + '"')

Answer: "[CLS]"

<ipython-input-131-7a74908cabf9>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  answer_start = torch.argmax(torch.tensor(start_scores))

In [132]:
# Start with the first token.
answer = tokens[answer_start]

# Select the remaining answer tokens and join them with whitespace.
for i in range(answer_start + 1, answer_end + 1):
    
    # If it's a subword token, then recombine it with the previous token.
    if tokens[i][0:2] == '##':
        answer += tokens[i][2:]
    
    # Otherwise, add a space then the token.
    else:
        answer += ' ' + tokens[i]

print('Answer: "' + answer + '"')

Answer: "[CLS]"

___
# 4. Visualizing Scores

In [124]:
import matplotlib.pyplot as plt
import seaborn as sns

# Use plot styling from seaborn.
sns.set(style='darkgrid')

# Increase the plot size and font size.
#sns.set(font_scale=1.5)
plt.rcParams["figure.figsize"] = (16,8)

In [125]:
# Pull the scores out of PyTorch Tensors and convert them to 1D numpy arrays.
s_scores = start_scores.detach().numpy().flatten()
e_scores = end_scores.detach().numpy().flatten()

# We'll use the tokens as the x-axis labels. In order to do that, they all need
# to be unique, so we'll add the token index to the end of each one.
token_labels = []
for (i, token) in enumerate(tokens):
    token_labels.append('{:} - {:>2}'.format(token, i))

In [126]:
# Create a barplot showing the start word score for all of the tokens.
ax = sns.barplot(x=token_labels, y=s_scores, ci=None)

# Turn the xlabels vertical.
ax.set_xticklabels(ax.get_xticklabels(), rotation=90, ha="center")

# Turn on the vertical grid to help align words to scores.
ax.grid(True)

plt.title('Start Word Scores')

plt.show()

KeyError: '[CLS] -  0'

In [ ]:
# Create a barplot showing the end word score for all of the tokens.
ax = sns.barplot(x=token_labels, y=e_scores, ci=None)

# Turn the xlabels vertical.
ax.set_xticklabels(ax.get_xticklabels(), rotation=90, ha="center")

# Turn on the vertical grid to help align words to scores.
ax.grid(True)

plt.title('End Word Scores')

plt.show()

___
## Alternate View

In [ ]:
import pandas as pd

# Store the tokens and scores in a DataFrame. 
# Each token will have two rows, one for its start score and one for its end
# score. The "marker" column will differentiate them. A little wacky, I know.
scores = []
for (i, token_label) in enumerate(token_labels):

    # Add the token's start score as one row.
    scores.append({'token_label': token_label, 
                   'score': s_scores[i],
                   'marker': 'start'})
    
    # Add  the token's end score as another row.
    scores.append({'token_label': token_label, 
                   'score': e_scores[i],
                   'marker': 'end'})
    
df = pd.DataFrame(scores)

In [ ]:
# Draw a grouped barplot to show start and end scores for each word.
# The "hue" parameter is where we tell it which datapoints belong to which
# of the two series.
g = sns.catplot(x="token_label", y="score", hue="marker", data=df,
                kind="bar", height=6, aspect=4)

# Turn the xlabels vertical.
g.set_xticklabels(g.ax.get_xticklabels(), rotation=90, ha="center")

# Turn on the vertical grid to help align words to scores.
g.ax.grid(True)

___
# 5. More Examples

In [13]:
def answer_question(question, answer_text):
    '''
    Takes a `question` string and an `answer_text` string (which contains the
    answer), and identifies the words within the `answer_text` that are the
    answer. Prints them out.
    '''
    # ======== Tokenize ========
    # Apply the tokenizer to the input text, treating them as a text-pair.
    input_ids = tokenizer.encode(question, answer_text)

    # Report how long the input sequence is.
    print('Query has {:,} tokens.\n'.format(len(input_ids)))

    # ======== Set Segment IDs ========
    # Search the input_ids for the first instance of the `[SEP]` token.
    sep_index = input_ids.index(tokenizer.sep_token_id)

    # The number of segment A tokens includes the [SEP] token istelf.
    num_seg_a = sep_index + 1

    # The remainder are segment B.
    num_seg_b = len(input_ids) - num_seg_a

    # Construct the list of 0s and 1s.
    segment_ids = [0]*num_seg_a + [1]*num_seg_b

    # There should be a segment_id for every input token.
    assert len(segment_ids) == len(input_ids)

    # ======== Evaluate ========
    # Run our example question through the model.
    start_scores, end_scores = model(torch.tensor([input_ids]), # The tokens representing our input text.
                                    token_type_ids=torch.tensor([segment_ids])) # The segment IDs to differentiate question from answer_text

    # ======== Reconstruct Answer ========
    # Find the tokens with the highest `start` and `end` scores.
    answer_start = torch.argmax(start_scores)
    answer_end = torch.argmax(end_scores)

    # Get the string versions of the input tokens.
    tokens = tokenizer.convert_ids_to_tokens(input_ids)

    # Start with the first token.
    answer = tokens[answer_start]

    # Select the remaining answer tokens and join them with whitespace.
    for i in range(answer_start + 1, answer_end + 1):
        
        # If it's a subword token, then recombine it with the previous token.
        if tokens[i][0:2] == '##':
            answer += tokens[i][2:]
        
        # Otherwise, add a space then the token.
        else:
            answer += ' ' + tokens[i]

    print('Answer: "' + answer + '"')

In [14]:
import textwrap

# Wrap text to 80 characters.
wrapper = textwrap.TextWrapper(width=80) 

bert_abstract = "We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers. Unlike recent language representation models (Peters et al., 2018a; Radford et al., 2018), BERT is designed to pretrain deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers. As a result, the pre-trained BERT model can be finetuned with just one additional output layer to create state-of-the-art models for a wide range of tasks, such as question answering and language inference, without substantial taskspecific architecture modifications. BERT is conceptually simple and empirically powerful. It obtains new state-of-the-art results on eleven natural language processing tasks, including pushing the GLUE score to 80.5% (7.7% point absolute improvement), MultiNLI accuracy to 86.7% (4.6% absolute improvement), SQuAD v1.1 question answering Test F1 to 93.2 (1.5 point absolute improvement) and SQuAD v2.0 Test F1 to 83.1 (5.1 point absolute improvement)."

print(wrapper.fill(bert_abstract))

We introduce a new language representation model called BERT, which stands for
Bidirectional Encoder Representations from Transformers. Unlike recent language
representation models (Peters et al., 2018a; Radford et al., 2018), BERT is
designed to pretrain deep bidirectional representations from unlabeled text by
jointly conditioning on both left and right context in all layers. As a result,
the pre-trained BERT model can be finetuned with just one additional output
layer to create state-of-the-art models for a wide range of tasks, such as
question answering and language inference, without substantial taskspecific
architecture modifications. BERT is conceptually simple and empirically
powerful. It obtains new state-of-the-art results on eleven natural language
processing tasks, including pushing the GLUE score to 80.5% (7.7% point absolute
improvement), MultiNLI accuracy to 86.7% (4.6% absolute improvement), SQuAD v1.1
question answering Test F1 to 93.2 (1.5 point absolute improvement) and SQuAD
v2.0 Test F1 to 83.1 (5.1 point absolute improvement).

In [15]:
question = "What does the 'B' in BERT stand for?"

answer_question(question, bert_abstract)

Query has 258 tokens.

TypeError: argmax(): argument 'input' (position 1) must be Tensor, not str

In [ ]:
question = "What are some example applications of BERT?"

answer_question(question, bert_abstract)